version: '3.8'

services:
  panoptikon:
    build: .
    container_name: panoptikon
    ports:
      - "6342:6342"
      - "6339:6339"
    environment:
      - HOST=127.0.0.1
      - PORT=6342
      - DATA_FOLDER=data
      - LOGLEVEL=INFO
      - ENABLE_CLIENT=true
      - CLIENT_HOST=127.0.0.1
      - CLIENT_PORT=6339
    volumes:
      - ./data:/app/data
