services:
  panoptikon:
    build: .
    container_name: panoptikon
    ports:
      - "6342:6342"
      - "6339:6339"
    environment:
      - HOST=0.0.0.0
      - PORT=6342
      - DATA_FOLDER=data
      - LOGLEVEL=INFO
      - ENABLE_CLIENT=true
      - CLIENT_HOST=0.0.0.0
      - CLIENT_PORT=6339
    volumes:
      - ./data:/app/data
      - ./panoptikon-ui:/app/src/searchui/panoptikon-ui
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
