[tool.poetry]
name = "panoptikon"
version = "0.1.0"
description = "AI-based media indexing, tagging, and semantic search engine for local files"
authors = ["reasv"]
license = "AGPL"
readme = "README.md"
packages = [
    { include = "panoptikon", from="src" },
    { include = "panoptikon.*", from="src" }
]

[tool.poetry.dependencies]
python = "^3.12"
gradio = "^4.37.2"
pillow = "^10.4.0"
imageio-ffmpeg = {extras = ["ffmpeg"], version = "^0.5.1"}
open-clip-torch = "^2.26.1"
chromadb = "^0.5.4"
python-doctr = {extras = ["torch"], version = "^0.8.1"}
timm = "^1.0.7"
python-dotenv = "^1.0.1"
faster-whisper = {git = "https://github.com/SYSTRAN/faster-whisper.git"}
sqlite-vec = "^0.0.1a36"
sqlite-path = "^0.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 80
