[tool.poetry]
name = "panoptikon"
version = "0.1.0"
description = "AI-based media indexing, tagging, and semantic search engine for local files"
authors = ["reasv"]
license = "AGPL"
readme = "README.md"
packages = [
    { include = "panoptikon", from="src" },
    { include = "panoptikon.*", from="src" }
]

[tool.poetry.dependencies]
python = "^3.12"
gradio = "^4.37.2"
pillow = "^10.4.0"
imageio-ffmpeg = {extras = ["ffmpeg"], version = "^0.5.1"}
paddleocr = "^2.8.0"
paddlepaddle-gpu = "^2.6.1"
open-clip-torch = "^2.26.1"
chromadb = "^0.5.4"
whisperx = "^3.1.5"
torch = {version = "^2.3.1+cu121", source = "pytorch_cuda"}
torchvision = {version = "^0.18.1+cu121", source = "pytorch_cuda"}
torchaudio = {version = "^2.3.1+cu121", source = "pytorch_cuda"}
python-doctr = {extras = ["torch"], version = "^0.8.1"}
timm = "^1.0.7"
python-dotenv = "^1.0.1"

[[tool.poetry.source]]
name = "pytorch_cuda"
url = "https://download.pytorch.org/whl/cu121"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
